### ISSUE TITLE
[BUG] Update check includes unsupported dependency updates

### ISSUE THREAD

**Issue by IngoMueller** [eliashaeussler/composer-update-check#9]
### PHP version

7.3.33

### Package version

1.2.0

### Operating system

Linux 3.10.0-1160.62.1.el7.x86_64

### Current behavior

The updatecheck reports an outdated version of an extension, although it does not run with the current PHP version.

### Expected behavior

The updatecheck respects my current PHP version

**Comment by eliashaeussler** [comment]
@IngoMueller I release version 1.3.0 which should solve this issue. Please test it out and come back if something does still not work for you.
